# -*- coding: utf-8 -*- 


PARTS = [
    # {"part": "", "play": "", "wait": 0},
    
    {"part": "аудиторія", "play": "audiitoriya", "wait": 0},
    {"part": "мама", "play": "mama", "wait": 0},
    {"part": "мила", "play": "miila", "wait": 0},
    {"part": "раму", "play": "ramu", "wait": 0},
    {"part": "шановні", "play": "shanovni", "wait": 0},
    {"part": "доброго", "play": "dobrogho", "wait": 0},
    {"part": "журі", "play": "zhuri", "wait": 0},
    {"part": "дня", "play": "dnya", "wait": 0},

    {"part": "академія", "play": "akademiya", "wait": 0},
    {"part": "мала", "play": "mala", "wait": 0},
    {"part": "молоді", "play": "molodi", "wait": 0},
    {"part": "наук", "play": "nauk", "wait": 0},
    {"part": "рівненська", "play": "rivnenswka", "wait": 0},
    {"part": "синтезу", "play": "siintezu", "wait": 0},
    {"part": "учнівської", "play": "uchnivswkoyi", "wait": 0},

    {"part": "липа", "play": "liipa", "wait": 0},
    {"part": "місячні", "play": "misyachni", "wait": 0},
    {"part": "мовленя", "play": "movlenya", "wait": 0},
    {"part": "ночі", "play": "nochi", "wait": 0},
    {"part": "шелестить", "play": "shelestiitw", "wait": 0},
    {"part": "система", "play": "siistema", "wait": 0},
    {"part": "весняні", "play": "vesnyani", "wait": 0},
    {"part": "знаєте", "play": "znayete", "wait": 0},
    {"part": "як", "play": "yak", "wait": 0},

    {"part": "джа", "play": "dzha", "wait": 0},
    {"part": "джо", "play": "dzho", "wait": 0},
    {"part": "дже", "play": "dzhe", "wait": 0},
    {"part": "джу", "play": "dzhu", "wait": 0},
    {"part": "джі", "play": "dzhi", "wait": 0},
    {"part": "джи", "play": "dzhii", "wait": 0},
    {"part": "джя", "play": "dzhya", "wait": 0},
    {"part": "джю", "play": "dzhyu", "wait": 0},
    {"part": "джє", "play": "dzhye", "wait": 0},

    {"part": "дза", "play": "dza", "wait": 0},
    {"part": "дзо", "play": "dzo", "wait": 0},
    {"part": "дзе", "play": "dze", "wait": 0},
    {"part": "дзу", "play": "dzu", "wait": 0},
    {"part": "дзі", "play": "dzi", "wait": 0},
    {"part": "дзи", "play": "dzii", "wait": 0},
    {"part": "дзя", "play": "dzya", "wait": 0},
    {"part": "дзю", "play": "dzyu", "wait": 0},
    {"part": "дзє", "play": "dzye", "wait": 0},

    {"part": "джь", "play": "dzhw", "wait": 0},
    {"part": "дзь", "play": "dzw", "wait": 0},

    {"part": "та", "play": "ta", "wait": 0},
    {"part": "то", "play": "to", "wait": 0},
    {"part": "те", "play": "te", "wait": 0},
    {"part": "ту", "play": "tu", "wait": 0},
    {"part": "ті", "play": "ti", "wait": 0},
    {"part": "ти", "play": "tii", "wait": 0},
    {"part": "тя", "play": "tya", "wait": 0},
    {"part": "тю", "play": "tyu", "wait": 0},
    {"part": "тє", "play": "tye", "wait": 0},

    {"part": "на", "play": "na", "wait": 0},
    {"part": "но", "play": "no", "wait": 0},
    {"part": "не", "play": "ne", "wait": 0},
    {"part": "ну", "play": "nu", "wait": 0},
    {"part": "ні", "play": "ni", "wait": 0},
    {"part": "ни", "play": "nii", "wait": 0},
    {"part": "ня", "play": "nya", "wait": 0},
    {"part": "ню", "play": "nyu", "wait": 0},
    {"part": "нє", "play": "nye", "wait": 0},

    {"part": "са", "play": "sa", "wait": 0},
    {"part": "со", "play": "so", "wait": 0},
    {"part": "се", "play": "se", "wait": 0},
    {"part": "су", "play": "su", "wait": 0},
    {"part": "сі", "play": "si", "wait": 0},
    {"part": "си", "play": "sii", "wait": 0},
    {"part": "ся", "play": "sya", "wait": 0},
    {"part": "сю", "play": "syu", "wait": 0},
    {"part": "сє", "play": "sye", "wait": 0},

    {"part": "ма", "play": "ma", "wait": 0},
    {"part": "мо", "play": "mo", "wait": 0},
    {"part": "ме", "play": "me", "wait": 0},
    {"part": "му", "play": "mu", "wait": 0},
    {"part": "мі", "play": "mi", "wait": 0},
    {"part": "ми", "play": "mii", "wait": 0},
    {"part": "мя", "play": "mya", "wait": 0},
    # {"part": "мю", "play": "myu", "wait": 0},
    {"part": "мє", "play": "mye", "wait": 0},

    {"part": "ра", "play": "ra", "wait": 0},
    {"part": "ро", "play": "ro", "wait": 0},
    {"part": "ре", "play": "re", "wait": 0},
    {"part": "ру", "play": "ru", "wait": 0},
    {"part": "рі", "play": "ri", "wait": 0},
    {"part": "ри", "play": "rii", "wait": 0},
    {"part": "ря", "play": "rya", "wait": 0},
    {"part": "рю", "play": "ryu", "wait": 0},
    {"part": "рє", "play": "rye", "wait": 0},

    {"part": "па", "play": "pa", "wait": 0},
    {"part": "по", "play": "po", "wait": 0},
    {"part": "пе", "play": "pe", "wait": 0},
    {"part": "пу", "play": "pu", "wait": 0},
    {"part": "пі", "play": "pi", "wait": 0},
    {"part": "пи", "play": "pii", "wait": 0},
    {"part": "пя", "play": "pya", "wait": 0},
    {"part": "пю", "play": "pyu", "wait": 0},
    {"part": "пє", "play": "pye", "wait": 0},

    {"part": "ла", "play": "la", "wait": 0},
    {"part": "ло", "play": "lo", "wait": 0},
    {"part": "ле", "play": "le", "wait": 0},
    {"part": "лу", "play": "lu", "wait": 0},
    {"part": "лі", "play": "li", "wait": 0},
    {"part": "ли", "play": "lii", "wait": 0},
    {"part": "ля", "play": "lya", "wait": 0},
    {"part": "лю", "play": "lyu", "wait": 0},
    {"part": "лє", "play": "lye", "wait": 0},

    {"part": "ва", "play": "va", "wait": 0},
    {"part": "во", "play": "vo", "wait": 0},
    {"part": "ве", "play": "ve", "wait": 0},
    {"part": "ву", "play": "vu", "wait": 0},
    {"part": "ві", "play": "vi", "wait": 0},
    {"part": "ви", "play": "vii", "wait": 0},
    {"part": "вя", "play": "vya", "wait": 0},
    {"part": "вю", "play": "vyu", "wait": 0},
    {"part": "вє", "play": "vye", "wait": 0},

    {"part": "ба", "play": "ba", "wait": 0},
    {"part": "бо", "play": "bo", "wait": 0},
    {"part": "бе", "play": "be", "wait": 0},
    {"part": "бу", "play": "bu", "wait": 0},
    {"part": "бі", "play": "bi", "wait": 0},
    {"part": "би", "play": "bii", "wait": 0},
    {"part": "бя", "play": "bya", "wait": 0},
    {"part": "бю", "play": "byu", "wait": 0},
    {"part": "бє", "play": "bye", "wait": 0},

    {"part": "ка", "play": "ka", "wait": 0},
    {"part": "ко", "play": "ko", "wait": 0},
    {"part": "ке", "play": "ke", "wait": 0},
    {"part": "ку", "play": "ku", "wait": 0},
    {"part": "кі", "play": "ki", "wait": 0},
    {"part": "ки", "play": "kii", "wait": 0},
    {"part": "кя", "play": "kya", "wait": 0},
    {"part": "кю", "play": "kyu", "wait": 0},
    {"part": "кє", "play": "kye", "wait": 0},

    {"part": "да", "play": "da", "wait": 0},
    {"part": "до", "play": "do", "wait": 0},
    {"part": "де", "play": "de", "wait": 0},
    {"part": "ду", "play": "du", "wait": 0},
    {"part": "ді", "play": "di", "wait": 0},
    {"part": "ди", "play": "dii", "wait": 0},
    {"part": "дя", "play": "dya", "wait": 0},
    {"part": "дю", "play": "dyu", "wait": 0},
    {"part": "дє", "play": "dye", "wait": 0},

    {"part": "га", "play": "gha", "wait": 0},
    {"part": "го", "play": "gho", "wait": 0},
    {"part": "ге", "play": "ghe", "wait": 0},
    {"part": "гу", "play": "ghu", "wait": 0},
    {"part": "гі", "play": "ghi", "wait": 0},
    {"part": "ги", "play": "ghii", "wait": 0},
    {"part": "гя", "play": "ghya", "wait": 0},
    {"part": "гю", "play": "ghyu", "wait": 0},
    {"part": "гє", "play": "ghye", "wait": 0},

    {"part": "жа", "play": "zha", "wait": 0},
    {"part": "жо", "play": "zho", "wait": 0},
    {"part": "же", "play": "zhe", "wait": 0},
    {"part": "жу", "play": "zhu", "wait": 0},
    {"part": "жі", "play": "zhi", "wait": 0},
    {"part": "жи", "play": "zhii", "wait": 0},
    {"part": "жя", "play": "zhya", "wait": 0},
    {"part": "жю", "play": "zhyu", "wait": 0},
    {"part": "жє", "play": "zhye", "wait": 0},

    {"part": "ша", "play": "sha", "wait": 0},
    {"part": "шо", "play": "sho", "wait": 0},
    {"part": "ше", "play": "she", "wait": 0},
    {"part": "шу", "play": "shu", "wait": 0},
    {"part": "ші", "play": "shi", "wait": 0},
    {"part": "ши", "play": "shii", "wait": 0},
    {"part": "шя", "play": "shya", "wait": 0},
    {"part": "шю", "play": "shyu", "wait": 0},
    {"part": "шє", "play": "shye", "wait": 0},

    {"part": "ґа", "play": "ga", "wait": 0},
    {"part": "ґо", "play": "go", "wait": 0},
    {"part": "ґе", "play": "ge", "wait": 0},
    {"part": "ґу", "play": "gu", "wait": 0},
    {"part": "ґі", "play": "gi", "wait": 0},
    {"part": "ґи", "play": "gii", "wait": 0},
    {"part": "ґя", "play": "gya", "wait": 0},
    {"part": "ґю", "play": "gyu", "wait": 0},
    {"part": "ґє", "play": "gye", "wait": 0},

    {"part": "за", "play": "za", "wait": 0},
    {"part": "зо", "play": "zo", "wait": 0},
    {"part": "зе", "play": "ze", "wait": 0},
    {"part": "зу", "play": "zu", "wait": 0},
    {"part": "зі", "play": "zi", "wait": 0},
    {"part": "зи", "play": "zii", "wait": 0},
    {"part": "зя", "play": "zya", "wait": 0},
    {"part": "зю", "play": "zyu", "wait": 0},
    {"part": "зє", "play": "zye", "wait": 0},

    {"part": "фа", "play": "fa", "wait": 0},
    {"part": "фо", "play": "fo", "wait": 0},
    {"part": "фе", "play": "fe", "wait": 0},
    {"part": "фу", "play": "fu", "wait": 0},
    {"part": "фі", "play": "fi", "wait": 0},
    {"part": "фи", "play": "fii", "wait": 0},
    {"part": "фя", "play": "fya", "wait": 0},
    {"part": "фю", "play": "fyu", "wait": 0},
    {"part": "фє", "play": "fye", "wait": 0},

    {"part": "ха", "play": "ha", "wait": 0},
    {"part": "хо", "play": "ho", "wait": 0},
    {"part": "хе", "play": "he", "wait": 0},
    {"part": "ху", "play": "hu", "wait": 0},
    {"part": "хі", "play": "hi", "wait": 0},
    {"part": "хи", "play": "hii", "wait": 0},
    {"part": "хя", "play": "hya", "wait": 0},
    {"part": "хю", "play": "hyu", "wait": 0},
    {"part": "хє", "play": "hye", "wait": 0},

    {"part": "ца", "play": "tsa", "wait": 0},
    {"part": "цо", "play": "tso", "wait": 0},
    {"part": "це", "play": "tse", "wait": 0},
    {"part": "цу", "play": "tsu", "wait": 0},
    {"part": "ці", "play": "tsi", "wait": 0},
    {"part": "ци", "play": "tsii", "wait": 0},
    {"part": "ця", "play": "tsya", "wait": 0},
    {"part": "цю", "play": "tsyu", "wait": 0},
    {"part": "цє", "play": "tsye", "wait": 0},

    {"part": "ча", "play": "cha", "wait": 0},
    {"part": "чо", "play": "cho", "wait": 0},
    {"part": "че", "play": "che", "wait": 0},
    {"part": "чу", "play": "chu", "wait": 0},
    {"part": "чі", "play": "chi", "wait": 0},
    {"part": "чи", "play": "chii", "wait": 0},
    {"part": "чя", "play": "chya", "wait": 0},
    {"part": "чю", "play": "chyu", "wait": 0},
    {"part": "чє", "play": "chye", "wait": 0},

    {"part": "ща", "play": "shcha", "wait": 0},
    {"part": "що", "play": "shcho", "wait": 0},
    {"part": "ще", "play": "shche", "wait": 0},
    {"part": "щу", "play": "shchu", "wait": 0},
    {"part": "щі", "play": "shchi", "wait": 0},
    {"part": "щи", "play": "shchii", "wait": 0},
    {"part": "щя", "play": "shchya", "wait": 0},
    {"part": "щю", "play": "shchyu", "wait": 0},
    {"part": "щє", "play": "shchye", "wait": 0},

    {"part": "йо", "play": "yo", "wait": 0},

    {"part": "бь", "play": "bw", "wait": 0},
    {"part": "вь", "play": "vw", "wait": 0},
    {"part": "гь", "play": "ghw", "wait": 0},
    {"part": "ґь", "play": "gw", "wait": 0},
    {"part": "дь", "play": "dw", "wait": 0},
    {"part": "жь", "play": "zhw", "wait": 0},
    {"part": "зь", "play": "zw", "wait": 0},
    {"part": "кь", "play": "kw", "wait": 0},
    {"part": "ль", "play": "lw", "wait": 0},
    {"part": "мь", "play": "mw", "wait": 0},
    {"part": "нь", "play": "nw", "wait": 0},
    {"part": "пь", "play": "pw", "wait": 0},
    {"part": "рь", "play": "rw", "wait": 0},
    {"part": "сь", "play": "sw", "wait": 0},
    {"part": "ть", "play": "tw", "wait": 0},
    {"part": "фь", "play": "fw", "wait": 0},
    {"part": "хь", "play": "hw", "wait": 0},
    {"part": "ць", "play": "tsw", "wait": 0},
    {"part": "чь", "play": "chw", "wait": 0},
    {"part": "шь", "play": "shw", "wait": 0},
    {"part": "щь", "play": "shchw", "wait": 0},

    {"part": "дж", "play": "dzh", "wait": 0},
    {"part": "дз", "play": "dz", "wait": 0},
    {"part": "б", "play": "b", "wait": 0},
    {"part": "в", "play": "v", "wait": 0},
    {"part": "г", "play": "gh", "wait": 0},
    {"part": "ґ", "play": "g", "wait": 0},
    {"part": "д", "play": "d", "wait": 0},
    {"part": "ж", "play": "zh", "wait": 0},
    {"part": "з", "play": "z", "wait": 0},
    {"part": "й", "play": "y", "wait": 0},
    {"part": "к", "play": "k", "wait": 0},
    {"part": "л", "play": "l", "wait": 0},
    {"part": "м", "play": "m", "wait": 0},
    {"part": "н", "play": "n", "wait": 0},
    {"part": "п", "play": "p", "wait": 0},
    {"part": "р", "play": "r", "wait": 0},
    {"part": "с", "play": "s", "wait": 0},
    {"part": "т", "play": "t", "wait": 0},
    {"part": "ф", "play": "f", "wait": 0},
    {"part": "х", "play": "h", "wait": 0},
    {"part": "ц", "play": "ts", "wait": 0},
    {"part": "ч", "play": "ch", "wait": 0},
    {"part": "ш", "play": "sh", "wait": 0},
    {"part": "щ", "play": "shch", "wait": 0},

    {"part": "а", "play": "a", "wait": 0},
    {"part": "о", "play": "o", "wait": 0},
    {"part": "е", "play": "e", "wait": 0},
    {"part": "у", "play": "u", "wait": 0},
    {"part": "і", "play": "i", "wait": 0},
    {"part": "и", "play": "ii", "wait": 0},
    {"part": "я", "play": "ya", "wait": 0},
    {"part": "ю", "play": "yu", "wait": 0},
    {"part": "є", "play": "ye", "wait": 0},
    {"part": "ї", "play": "yi", "wait": 0},

    {"part": "0", "play": "0", "wait": 0},
    {"part": "1", "play": "1", "wait": 0},
    {"part": "2", "play": "2", "wait": 0},
    {"part": "3", "play": "3", "wait": 0},
    {"part": "4", "play": "4", "wait": 0},
    {"part": "5", "play": "5", "wait": 0},
    {"part": "6", "play": "6", "wait": 0},
    {"part": "7", "play": "7", "wait": 0},
    {"part": "8", "play": "8", "wait": 0},
    {"part": "9", "play": "9", "wait": 0},

    {"part": "'", "play": "", "wait": 200},
    {"part": " ", "play": "", "wait": 400},
    {"part": ",", "play": "", "wait": 300},
    {"part": ".", "play": "", "wait": 800},
    {"part": "!", "play": "", "wait": 800},
    {"part": "?", "play": "", "wait": 800},
    {"part": "-", "play": "", "wait": 300},
    {"part": "\n", "play": "", "wait": 400}
]
